services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    TemplateMakerBundle\Controller\:
        resource: '../../Controller'
        public: true
        tags: ['controller.service_arguments']

    TemplateMakerBundle\Service\:
        resource: '../../Service'
        public: true

    template.maker.installer:
        class: TemplateMakerBundle\Service\Installer
        public: true
        autowire: true
